/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Terminal state detected by state parsers */
export const enum State {
  Starting = 'Starting',
  Idle = 'Idle',
  Thinking = 'Thinking',
  ToolRunning = 'ToolRunning',
  Confirming = 'Confirming',
  Error = 'Error'
}
/** Type of confirmation dialog */
export const enum ConfirmType {
  Options = 'Options',
  YesNo = 'YesNo'
}
/** Status phase */
export const enum StatusPhase {
  Thinking = 'Thinking',
  ToolRunning = 'ToolRunning',
  Unknown = 'Unknown'
}
/** Tool execution status */
export const enum ToolStatus {
  Running = 'Running',
  Completed = 'Completed'
}
/** Fingerprint category */
export const enum FingerprintCategory {
  Spinner = 'Spinner',
  Statusbar = 'Statusbar',
  Prompt = 'Prompt',
  Separator = 'Separator',
  Assistant = 'Assistant',
  Tool = 'Tool',
  Error = 'Error',
  Confirm = 'Confirm'
}
/** State detection result */
export interface StateResult {
  state: State
  confidence: number
  needsTrustConfirm?: boolean
  confirmType?: ConfirmType
}
/** Confirm option */
export interface ConfirmOption {
  key: string
  label: string
  isDefault: boolean
}
/** Tool info in confirmation */
export interface ToolInfo {
  name: string
  mcpServer?: string
  params: Record<string, string>
}
/** Confirmation dialog info */
export interface ConfirmInfo {
  confirmType: ConfirmType
  prompt: string
  options?: Array<ConfirmOption>
  tool?: ToolInfo
  rawPrompt: string
}
/** Status bar info */
export interface StatusInfo {
  spinner: string
  statusText: string
  phase: StatusPhase
  interruptible: boolean
}
/** Title parse result */
export interface TitleInfo {
  taskName?: string
  spinnerState: string
  isProcessing: boolean
}
/** Tool output result */
export interface ToolOutput {
  toolName: string
  params: Record<string, any>
  output?: string
  durationMs?: number
  status: ToolStatus
}
/** Fingerprint match result */
export interface FingerprintMatch {
  fingerprintId: string
  matched: boolean
  captures?: Array<string>
  lineIndex?: number
}
/** Fingerprint hints */
export interface FingerprintHints {
  hasSpinner: boolean
  hasPrompt: boolean
  hasToolOutput: boolean
  hasConfirmDialog: boolean
  hasError: boolean
}
/** Fingerprint extraction result */
export interface FingerprintResult {
  hints: FingerprintHints
  matches: Record<string, FingerprintMatch>
}
/** Detect state from terminal lines (convenience function) */
export declare function detectState(lines: Array<string>): StateResult | null
/** Detect confirmation dialog (convenience function) */
export declare function detectConfirm(lines: Array<string>): ConfirmInfo | null
/** Parse status bar (convenience function) */
export declare function parseStatus(lines: Array<string>): StatusInfo | null
/** Parse tool output (convenience function) */
export declare function parseToolOutput(lines: Array<string>): ToolOutput | null
/** Extract fingerprints (convenience function) */
export declare function extractFingerprints(lines: Array<string>): FingerprintResult
/** Known tool names */
export declare function knownTools(): Array<string>
/** Spinner characters used by Claude Code */
export declare function spinnerChars(): Array<string>
/** Claude Code state parser */
export declare class StateParser {
  constructor()
  /** Detect state from terminal lines */
  detect(lines: Array<string>, currentState?: State | undefined | null): StateResult | null
}
/** Claude Code confirmation parser */
export declare class ConfirmParser {
  constructor()
  /** Detect and parse confirmation dialog */
  detect(lines: Array<string>): ConfirmInfo | null
  /** Format a response for the terminal */
  formatConfirm(): string
  /** Format a deny response for the terminal */
  formatDeny(confirmType: ConfirmType): string
  /** Format a select response for the terminal */
  formatSelect(option: number): string
}
/** Claude Code status parser */
export declare class StatusParser {
  constructor()
  /** Check if context can be parsed as status */
  canParse(lines: Array<string>): boolean
  /** Parse status bar information */
  parse(lines: Array<string>): StatusInfo | null
}
/** Claude Code title parser */
export declare class TitleParser {
  constructor()
  /** Check if title can be parsed */
  canParse(title: string): boolean
  /** Parse terminal title */
  parse(title: string): TitleInfo | null
}
/** Claude Code tool output parser */
export declare class ToolOutputParser {
  constructor()
  /** Check if context can be parsed as tool output */
  canParse(lines: Array<string>): boolean
  /** Parse tool output */
  parse(lines: Array<string>): ToolOutput | null
}
/** Fingerprint registry for pattern matching */
export declare class Registry {
  /** Create a new registry with default Claude Code fingerprints */
  constructor()
  /** Extract fingerprints from terminal lines */
  extract(lines: Array<string>): FingerprintResult
  /** Quick check for spinner */
  hasSpinner(lines: Array<string>): boolean
  /** Quick check for prompt */
  hasPrompt(lines: Array<string>): boolean
  /** Quick check for error */
  hasError(lines: Array<string>): boolean
}
